server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/advisor_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root      # 请改为你的用户名
    password: lyb050527      # 请改为你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # 开发阶段使用 update 自动建表
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.advisor_backend.model.dto.entity

jwt:
  secret: your-256-bit-secret
  expiration: 3600          # 单位：秒

logging:
  level:
    root: INFO
    com.yourorg: DEBUG
