server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/advisor_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

    username: root
    password: lyb050527
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.advisor_backend.model.dto.entity

jwt:
  secret: c3lzdGVtLWJhY2tlbmQtYWR2aXNvci1zcHJpbmctc2VjdXJpdHktand0LXNlY3JldC1rZXkK
  expiration: 86400000 # 24 hours

logging:
  level:
    root: INFO
    com.yourorg: DEBUG

